### ISSUE TITLE
Resolve License Compliance Issues

### ISSUE THREAD

**Issue by HelipengTony** [HelipengTony/ouorz-mono#300]
^ditto

**Comment by stefan-hdt** [comment]
What is the license compliance issue? Maybe I can help...

**Comment by HelipengTony** [comment]
@stefan-hdt This is a report of all licensing issues found by [FOSSA](https://app.fossa.com/projects/git%2Bgithub.com%2FHelipengTony%2Fouorz-mono?ref=badge_large):

[issues.csv](https://github.com/HelipengTony/ouorz-mono/files/9030755/issues.csv)

I'm not exactly sure how to fix those issues, so would greatly appreciate your help :)
